name: Test action
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Arrange
      -

      - name: Act
        run: |
          node "$GITHUB_ACTION_PATH/assets/assert.js"


      - name: Act - call some mocked functions
        run: |
          kubectl version
          kustomize edit set image my-image
          kustomize edit add configmap my-config --from-literal="labels=my-123"
          kustomize build | kubectl apply -f -


      - name: Assert - With multiple args
        uses: './'
        with:
          commands: kustomize
          assert-args: |
            ["edit", "set", "image", "my-image"]
            ["edit", "add", "configmap", "my-config", "--from-literal=labels=my-[0-9]+"]
            ["build"]

      - name: Assert - Using a specific call-index
        uses: './'
        with:
          commands: kubectl
          assert-call-index: 1
          assert-args: |
            ["apply", "-f", "-"]
